name       : haskell-comonad
version    : 5
release    : 1
source     :
    - http://hackage.haskell.org/package/comonad-5/comonad-5.tar.gz : 78e5b19da5b701d14ceb2ca19191cc6205b2024ff2f71b754f5e949faa19cb2a
license    : BSD-3-Clause
component  : programming.haskell
summary    : Comonads
description: |
    Comonads
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-contravariant
    - haskell-distributive
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
