name       : haskell-comonad
version    : 5.0.3
release    : 4
source     :
    - https://hackage.haskell.org/package/comonad-5.0.3/comonad-5.0.3.tar.gz : a7f4584d634051123c547f0d10f88eaf23d99229dbd01dfdcd98cddd41e54df6
license    : BSD-3-Clause
component  : programming.haskell
summary    : Comonads
description: |
    Comonads
builddeps  :
    - ghc-devel
    - haskell-cabal-install
    - haskell-contravariant
    - haskell-distributive
    - haskell-semigroups
setup      : |
    sed -i "s|Custom|Simple|" comonad.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
