name       : haskell-comonad
version    : 5.0.6
release    : 5
source     :
    - https://hackage.haskell.org/package/comonad-5.0.6/comonad-5.0.6.tar.gz : 77cfb016acd1747b892c31b82daf0de93f508ba775d62562d376b354adb88fae
license    : BSD-3-Clause
component  : programming.haskell
summary    : Comonads
description: |
    Comonads
builddeps  :
    - haskell-cabal-install
    - haskell-contravariant-devel
    - haskell-distributive-devel
    - haskell-semigroups-devel
    - haskell-transformers-compat-devel
rundeps    :
    - devel:
        - haskell-contravariant-devel
        - haskell-distributive-devel
        - haskell-semigroups-devel
        - haskell-transformers-compat-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
